[package]
name = "kusari"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { version = "0.23.19" }
rustls-pki-types = "1.10.0"
url = "2.5.4"
tokio = { version = "1.41.1", features = ["full"]}
tokio-rustls = { version = "0.26.0" }
webpki-roots = "0.26.7"
bytes = "1.9.0"
http = "1.1.0"